export const banners = [
    {
      imageUrl: "https://picsum.photos/1200/600?random=1",
      title: "My Name, My Pride",
      description: "100 Visiting Cards at Rs 200",
      buttons: [{ text: "Shop Now", color: "blue" }],
    },
    {
      imageUrl: "https://picsum.photos/1200/600?random=2",
      title: "Wear Your Brand",
      description: "Starting at Rs. 550",
      buttons: [
        { text: "Custom Polo T-shirts", color: "blue" },
        { text: "Custom T-shirts", color: "white" },
      ],
    },
  ];
  
  export const categories = [
    { id: 1, name: "Visiting Cards", img: "https://picsum.photos/200/200?random=1" },
    { id: 2, name: "Custom Polo T-shirts", img: "https://picsum.photos/200/200?random=2" },
    { id: 3, name: "Office Shirts", img: "https://picsum.photos/200/200?random=3" },
    { id: 4, name: "Custom T-shirts", img: "https://picsum.photos/200/200?random=4" },
    { id: 5, name: "Custom Stamps & Ink", img: "https://picsum.photos/200/200?random=5" },
    { id: 6, name: "Photo Gifts", img: "https://picsum.photos/200/200?random=6" },
    { id: 7, name: "Labels, Stickers & Packaging", img: "https://picsum.photos/200/200?random=7" },
    { id: 8, name: "Custom Stationery", img: "https://picsum.photos/200/200?random=8" },
    { id: 9, name: "Signs, Posters & Marketing Materials", img: "https://picsum.photos/200/200?random=9" },
  ];
  
  export const recommendedProducts = [
    {
      id: 1,
      title: "Basics High-Speed HDMI Cable",
      description: "High-speed HDMI cable",
      offer: "Min. 50% Off",
      img: "https://picsum.photos/300/300?random=1",
      price: 360,
      ratingCount: 125,
      bestDeal: true,
      category: "Electronics",
    },
    {
      id: 2,
      title: "Custom Polo T-shirt",
      description: "Customizable polo t-shirt",
      offer: "Min. 50% Off",
      img: "https://picsum.photos/300/300?random=2",
      price: 250,
      ratingCount: 100,
      bestDeal: false,
      category: "Men",
    },
    {
      id: 3,
      title: "Photo Frame",
      description: "High-quality photo frame",
      offer: "Min. 50% Off",
      img: "https://picsum.photos/300/300?random=3",
      price: 150,
      ratingCount: 80,
      bestDeal: true,
      category: "Women",
    },
    {
      id: 4,
      title: "Wall Art",
      description: "Beautiful wall art",
      offer: "Min. 50% Off",
      img: "https://picsum.photos/300/300?random=4",
      price: 200,
      ratingCount: 90,
      bestDeal: false,
      category: "Electronics",
    },
    {
      id: 5,
      title: "Decorative Pillow",
      description: "Soft and stylish pillow",
      offer: "Min. 50% Off",
      img: "https://picsum.photos/300/300?random=5",
      price: 100,
      ratingCount: 70,
      bestDeal: true,
      category: "Women",
    },
    {
      id: 6,
      title: "Canvas Print",
      description: "Artistic canvas print",
      offer: "Min. 50% Off",
      img: "https://picsum.photos/300/300?random=6",
      price: 180,
      ratingCount: 110,
      bestDeal: false,
      category: "Men",
    },
  ];
  