import banner1 from '../assets/banner/banner1.png';
import banner2 from '../assets/banner/banner2.png';

export const banners = [
    {
      imageUrl: banner1,
      title: "Designed for Success",
      description: "Elegant & Personalized Office Essentials.",
      buttons: [
        { text: "Shop Now", color: "blue", link: "/category/Custom%20Stationery" }, // Add link
      ],
    },
    {
      imageUrl: banner2,
      title: "Wear Your Brand",
      description: "Dress the Part, Impress the World.",
      buttons: [
        { text: "Custom T-shirts", color: "blue", link: "/category/Custom%20T-shirts" },
        { text: "Custom Caps", color: "white", link: "/category/Custom%20caps" },
      ],
    },
  ];

  export const products = [
    {
        id: 1,
        title: "HDMI Cable",
        description: "High-speed HDMI cable",
        offer: "Min. 50% Off",
        img: "https://picsum.photos/300/300?random=1",
        price: 360,
        ratingCount: 125,
        bestDeal: true,
        category: "Custom Polo T-shirts",
        recommended: true,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=1-1",
            "https://picsum.photos/150/150?random=1-2",
            "https://picsum.photos/150/150?random=1-3",
            "https://picsum.photos/150/150?random=1-4",
            "https://picsum.photos/150/150?random=1-5",
        ],
    },
    {
      id: 2,
      title: "Bluetooth Speaker",
      description: "The garments labelled as Committed are products that have been produced using sustainable fibres or processes, reducing their environmental impact.",
      offer: "40% Off",
      img: "https://picsum.photos/900/900?random=2",
      price: 1200,
      ratingCount: 90,
      bestDeal: false,
      category: "Custom Polo T-shirts",
      recommended: true,
      thumbnailImages: [
          "https://picsum.photos/900/900?random=2-1",
          "https://picsum.photos/150/150?random=2-2",
          "https://picsum.photos/150/150?random=2-3",
          "https://picsum.photos/150/150?random=2-4",
          "https://picsum.photos/150/150?random=2-5",
      ],
  },
    {
        id: 3,
        title: "Smartwatch",
        description: "The garments labelled as Committed are products that have been produced using sustainable fibres or processes, reducing their environmental impact.",
        offer: "25% Off",
        img: "https://picsum.photos/300/300?random=3",
        price: 2999,
        ratingCount: 150,
        bestDeal: true,
        category: "Custom Polo T-shirts",
        recommended: false,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=3-1",
            "https://picsum.photos/150/150?random=3-2",
            "https://picsum.photos/150/150?random=3-3",
            "https://picsum.photos/150/150?random=3-4",
            "https://picsum.photos/150/150?random=3-5",
        ],
    },
    {
        id: 4,
        title: "Wireless Earbuds",
        description: "Noise-cancelling earbuds",
        offer: "30% Off",
        img: "https://picsum.photos/300/300?random=4",
        price: 2499,
        ratingCount: 200,
        bestDeal: true,
        category: "Audio",
        recommended: true,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=4-1",
            "https://picsum.photos/150/150?random=4-2",
            "https://picsum.photos/150/150?random=4-3",
            "https://picsum.photos/150/150?random=4-4",
            "https://picsum.photos/150/150?random=4-5",
        ],
    },
    {
        id: 5,
        title: "Gaming Mouse",
        description: "RGB Gaming mouse",
        offer: "35% Off",
        img: "https://picsum.photos/300/300?random=5",
        price: 899,
        ratingCount: 80,
        bestDeal: false,
        category: "Custom Polo T-shirts",
        recommended: false,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=5-1",
            "https://picsum.photos/150/150?random=5-2",
            "https://picsum.photos/150/150?random=5-3",
            "https://picsum.photos/150/150?random=5-4",
            "https://picsum.photos/150/150?random=5-5",
        ],
    },
    {
        id: 6,
        title: "Mechanical Keyboard",
        description: "RGB Mechanical Keyboard",
        offer: "20% Off",
        img: "https://picsum.photos/300/300?random=6",
        price: 3499,
        ratingCount: 120,
        bestDeal: true,
        category: "Accessories",
        recommended: true,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=6-1",
            "https://picsum.photos/150/150?random=6-2",
            "https://picsum.photos/150/150?random=6-3",
            "https://picsum.photos/150/150?random=6-4",
            "https://picsum.photos/150/150?random=6-5",
        ],
    },
    {
        id: 7,
        title: "Smart TV",
        description: "4K Ultra HD Smart TV",
        offer: "15% Off",
        img: "https://picsum.photos/300/300?random=7",
        price: 3999,
        ratingCount: 250,
        bestDeal: false,
        category: "Electronics",
        recommended: true,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=7-1",
            "https://picsum.photos/150/150?random=7-2",
            "https://picsum.photos/150/150?random=7-3",
            "https://picsum.photos/150/150?random=7-4",
            "https://picsum.photos/150/150?random=7-5",
        ],
    },
    {
        id: 8,
        title: "Laptop Cooling Pad",
        description: "Laptop cooling stand",
        offer: "50% Off",
        img: "https://picsum.photos/300/300?random=8",
        price: 1199,
        ratingCount: 75,
        bestDeal: false,
        category: "Accessories",
        recommended: false,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=8-1",
            "https://picsum.photos/150/150?random=8-2",
            "https://picsum.photos/150/150?random=8-3",
            "https://picsum.photos/150/150?random=8-4",
            "https://picsum.photos/150/150?random=8-5",
        ],
    },
    {
        id: 9,
        title: "External Hard Drive",
        description: "1TB External HDD",
        offer: "45% Off",
        img: "https://picsum.photos/300/300?random=9",
        price: 4999,
        ratingCount: 180,
        bestDeal: true,
        category: "Storage",
        recommended: true,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=9-1",
            "https://picsum.photos/150/150?random=9-2",
            "https://picsum.photos/150/150?random=9-3",
            "https://picsum.photos/150/150?random=9-4",
            "https://picsum.photos/150/150?random=9-5",
        ],
    },
    {
        id: 10,
        title: "Ring Light",
        description: "Dimmable LED Ring Light",
        offer: "30% Off",
        img: "https://picsum.photos/300/300?random=10",
        price: 1599,
        ratingCount: 110,
        bestDeal: false,
        category: "Accessories",
        recommended: true,
        thumbnailImages: [
            "https://picsum.photos/150/150?random=10-1",
            "https://picsum.photos/150/150?random=10-2",
            "https://picsum.photos/150/150?random=10-3",
            "https://picsum.photos/150/150?random=10-4",
            "https://picsum.photos/150/150?random=10-5",
        ],
    },
];

  // Breadcrumb Data
  export const breadcrumbs = [
    { label: "Home", href: "/" },
    { label: "Search", href: "/search" },
    { label: "Shop", href: "/products" }
  ];

  export const announcementMessage = "🎉 Free Shipping on Orders Over $50.00";

  export const contactInfo = {
    phone: "+1 666 234 8888",
    email: "sales@thinkprint.shop",
    address: "2163 Phillips Gap Rd, West Jefferson, North Carolina, United States",
    openTime: [
        { day: "Mon - Sat", time: "7:30am - 8:00pm PST" },
        { day: "Sunday", time: "9:00am - 5:00pm PST" },
    ],
};

  